services:

  ollama:
    build: ollama
    ports: 
      - 11434:11434
    volumes:
      - tutorial-vol:/ollama
    networks:
      - rag-net
    entrypoint: ["usr/bin/bash", "/pull-ollama.sh"]

  rag_agent:
    build: rag_agent
    ports:
      - 8000:8000
    volumes:
      - ./rag_agent:/rag_agent
    networks:
      - rag-net
    depends_on:
      - ollama
  
  streamlit-app:
    build: streamlit_app
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ENABLECORS=false
    volumes:
      - ./streamlit_app:/streamlit_app
    networks:
      - rag-net
    depends_on:
      - rag_agent

networks:
  rag-net:
    driver: bridge

volumes:
  tutorial-vol:
    driver: local
  
  